### PR TITLE
Added filtering function based on issue description

### PR DESCRIPTION
**Pull request by gallenaxel**
Function which filters the chosen dataframe based on the following parameters:

Variables `deltaRLep2ndClosestBJet`, `LJet_m_plus_RCJet_m_12`, `bb_m_for_minDeltaR` for `jet_n == 6 AND bjet_n ==4`. 

This yields the following pre-post event counts:

Background events before filter: 123951
Background events after filter: 205
Signal events before filter: 7578
Signal events after filter: 376

Does this make sense @olgeet ?

### CODE REVIEW

**Comment by olgeet** [comment]
@giuliaripellino Actually how much integrated lumi do we have? is it actually just 1/10 of the full dataset?

**Comment by giuliaripellino** [comment]
The SU2L_25_500 signal sample had 50k generated events. The data had 134175832+91944826=226120658 single electron+muon events.
I have no idea what lumi that partial CMS dataset corresponds to (and this information is not provided with the open data). Can we scale the signal to number of events instead of lumi? So give the signal events a weight = sigma_sig/N_sig,raw * N_bkg/sigma_bkg so that N_sig,scaled/N_bkg=sigma_sig/sigma_bkg

**Comment by giuliaripellino** [comment]
> Can we get @giuliaripellino 's opinion also? (And Rebeca if we get her on here) The number of background events seems to small to me. The (pre-fit, weighted) background yields in the Dark Meson analysis in a similar region: 1 lep, HT>300GeV, njets==6, nbjets==4: 2742 +- 17 The number of signal events have to be weighted by cross-section and lumi I guess? So harder to say. Did we start with 10,000 events?

I think here we should not compare absolute number of events but rather the SR efficiency. So how large fraction of bkg events are kept in the SR?

**Comment by giuliaripellino** [comment]
> The SU2L_25_500 signal sample had 50k generated events. The data had 134175832+91944826=226120658 single electron+muon events. I have no idea what lumi that partial CMS dataset corresponds to (and this information is not provided with the open data). Can we scale the signal to number of events instead of lumi? So give the signal events a weight = sigma_sig/N_sig,raw * N_bkg/sigma_bkg so that N_sig,scaled/N_bkg=sigma_sig/sigma_bkg. Then we take sigma_bkg as the pp x-sec at 80 mb.

Never mind! I found the lumi info here: http://opendata.cern.ch/record/1055/files/Run2015Dlumi.txt
We have data corresponding to 2.256382381 /fb

**Comment by olgeet** [comment]
Cross-section for 25_500: 0.01892 pb (from Jochen's dark meson analysis samples https://gitlab.cern.ch/darkmesonsearch/darkframework/-/blob/master/resources/XSection-MC16-13TeV.data?ref_type=heads)

**Pull request merged**
